package analizadores;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.io.OutputStream;
import javax.swing.JTextArea;

/**
 *
 * @author carlo
 */
public class FrmPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnAnalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtCadenaTexto = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        areahistorial = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.orange);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 132, 28));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculadora");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 30));

        BtnAnalizar.setBackground(new java.awt.Color(255, 204, 51));
        BtnAnalizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnAnalizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAnalizar.setText("Calcular");
        BtnAnalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAnalizarMouseClicked(evt);
            }
        });
        BtnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnalizarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        TxtCadenaTexto.setColumns(20);
        TxtCadenaTexto.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        TxtCadenaTexto.setRows(5);
        jScrollPane2.setViewportView(TxtCadenaTexto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 400, 173));

        areahistorial.setEditable(false);
        areahistorial.setColumns(20);
        areahistorial.setRows(5);
        jScrollPane1.setViewportView(areahistorial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 400, 140));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Historial de Operaciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizadores/Fondocalc.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void interpretar(String path) {
        analizadores.Sintactico pars;
        try {
            pars=new analizadores.Sintactico(new analizadores.Lexico(new FileInputStream(path)));
            pars.parse();
        } catch (Exception ex) {
            System.out.println("Error fatal en compilación de entrada.");
            System.out.println("Causa: "+ex.getCause());
        }
    }
    
    private void BtnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnalizarActionPerformed
        File archivo = new File("archivo.txt");
        PrintWriter escribir;
        try{
            clearScreen();
            escribir = new PrintWriter(archivo);
            escribir.print(TxtCadenaTexto.getText());
            escribir.close();
            interpretar("archivo.txt");
            areahistorial.append(TxtCadenaTexto.getText());
        } catch(FileNotFoundException ex){
            System.out.println("Inconveniente con el archivo: " + archivo + " Exception: " + ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BtnAnalizarActionPerformed

    public static void clearScreen() throws IOException, InterruptedException {  
        new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
    }
    

    public static void openTerminal() throws IOException {  
        Runtime rt = Runtime.getRuntime();
        rt.exec("cmd.exe /c start cd C:\\Various\\University\\2022\\Semestre 4\\Compiladores\\Trabajos\\NetBeans\\Proyecto_Calculadora\\dist");
    }

    
    private void BtnAnalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAnalizarMouseClicked
        
    }//GEN-LAST:event_BtnAnalizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnalizar;
    private javax.swing.JTextArea TxtCadenaTexto;
    private javax.swing.JTextArea areahistorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
