
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NEGATIVO = 15;
  public static final int COMA = 5;
  public static final int POTENCIA = 11;
  public static final int LineTerminator = 2;
  public static final int SUMA = 7;
  public static final int ENTERO = 13;
  public static final int RAIZ = 12;
  public static final int MULTIPLICACION = 9;
  public static final int EOF = 0;
  public static final int REAL = 14;
  public static final int error = 1;
  public static final int DIVISION = 10;
  public static final int PARENTESIS_CIERRE = 4;
  public static final int RESTA = 8;
  public static final int PUNTODECIMAL = 6;
  public static final int PARENTESIS_APERTURA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LineTerminator",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "COMA",
  "PUNTODECIMAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "RAIZ",
  "ENTERO",
  "REAL",
  "NEGATIVO"
  };
}

